version: "2"

run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goimports
    - misspell
    - unconvert
    - whitespace
    - revive

linters-settings:
  goimports:
    local-prefixes: weather-app
  gosec:
    excludes:
      - G107

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
