run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goimports
    - misspell
    - unconvert
    - whitespace
    - revive

linters-settings:
  goimports:
    local-prefixes: weather-app
